### ISSUE TITLE
Folh1 alleles do not autocomplete

### ISSUE THREAD

**Issue by viomunoz** [mpi2/impc-publication-curation#1]
Alelles for Folh1 are not available in the allele list / do not show up. They are in our website:
https://www.mousephenotype.org/data/genes/MGI:1858193

**Comment by viomunoz** [comment]
Paper topic was possible on protein PSMA/GCPII

**Comment by ficolo** [comment]
Fixed

**Comment by ficolo** [comment]
Fixed

![Screenshot 2019-08-05 at 14 23 24](https://user-images.githubusercontent.com/2343039/62467868-a8fd7c80-b78c-11e9-9bcb-37858918d946.png)
