### ISSUE TITLE
Necab2 and Scgn alleles do not autocomplete

### ISSUE THREAD

**Issue by viomunoz** [mpi2/impc-publication-curation#2]
For paper:
Ca2+-binding protein NECAB2 facilitates inflammatory pain hypersensitivity.
[Full text][Cites IMPC Paper (PMID:21677750)]Zhang MD, Su J, Adori C, Cinquina V, Malenczyk K, Girach F, Peng C, Ernfors P, Löw P, Borgius L, Kiehn O, Watanabe M, Uhlén M, Mitsios N, Mulder J, Harkany T, Hökfelt T.The Journal of clinical investigation | Mon Jul 30 01:00:00 BST 2018 

Need to add alleles :
	Necab2<tm1a(KOMP)Wtsi>
	Scgn<tm1a(KOMP)Wtsi>

**Comment by viomunoz** [comment]
Typed them in manually, cannot check whether they got saved (cannot find the paper again as filter in IMPC website does not work and in the Reviewed tab there is no free text option)

**Comment by ficolo** [comment]
Fixed

**Comment by ficolo** [comment]
Fixed
