### ISSUE TITLE
Complex cases

### ISSUE THREAD

**Issue by Gustems** [mpi2/impc-publication-curation#20]
I just found one complex example, which by the way is already in our list of publications (you did not have the very last version, but this not a problem...).
This paper:
<img width="1362" alt="image" src="https://user-images.githubusercontent.com/53742072/62457234-a2660980-b77a-11e9-92f1-b272f6481c70.png">
mentions 3 EMMA strains. Two of them were obtained from EMMA for this work and the third one was generated by the authors and submitted to EMMA afterwards.
As you see, I have entered 3 alleles and in the order ID field, 2 order IDs and the corresponding new EMMA strain. Would it be possible to link them one to one and have three rows in the csv file?

**Comment by ficolo** [comment]
I have made an update to the input fields for the order id and the emma id, now you can put several ids:

![Screenshot 2019-08-09 at 15 59 18](https://user-images.githubusercontent.com/2343039/62788425-c13c0700-babe-11e9-9a55-5d47134ac025.png)

I'll be releasing this version next week.
