### ISSUE TITLE
Multiple IDs should match one to one

### ISSUE THREAD

**Issue by Gustems** [mpi2/impc-publication-curation#24]
Hola Federico,

I started working again after summer holidays last week, but I haven’t had time till today to have a look at your last releases. It looks really good, the new features will help us a lot.

However, for the case where we had several strains in one publication, I still see some improvement needed:
![Screen Shot 2019-09-10 at 13 20 58](https://user-images.githubusercontent.com/53742072/64610537-bcc18180-d3cf-11e9-95c7-6afa1d33aa4a.png)

After your last changes, it is possible to record more than one request ID, and also to record the EMMA ID in case the strain was not requested from EMMA, but the publication describes a strain deposited at EMMA. This is great, but it should be possible to record which allele is related to which request ID or EMMA ID in a 1 to 1 relationship, as indicated above by the red arrows.

Furthermore, when downloading the csv file, this one to one relationship should be displayed, as corrected here from the current csv:
![Screen Shot 2019-09-10 at 13 23 38](https://user-images.githubusercontent.com/53742072/64610585-d4006f00-d3cf-11e9-8ddb-483444e1d0d8.png)

Please let me know if you need more information from our side. 

Many thanks again and best regards,

Montse

**Comment by ficolo** [comment]
Thanks for your feedback.

That is gonna be challenging with the current user interface, so I gonna try to implement an input that can hold together the values (allele -> order or submission id) that are supposed to be linked.
