### ISSUE TITLE
Fix invalid alleles found in publication list

### ISSUE THREAD

**Issue by viomunoz** [mpi2/impc-publication-curation#36]
**Issue:** 
An internal user has reported invalid alleles in the IMPC-related publication list. 

**Requirement:**
Need to trace and fix, as appropriate.

**List of invalid alleles:**
Kdm4c<tm1Wcs> Smyd5<tm1Wcs>
Dot1l<tm1Wcs>
Phf20<tm1Wcs>
Brd8<tm1Wcs>
Setdb1<tm1Wcs>
Kmt5b<tm1Wcs>
Ing3<tm1Wcs>
Cbx1<tm1Wcs>
Ddx27<tm1Wcs>
Epc2<tm1Wcs>
Mier1<tm1Wcs>
Supv3l1<tm1Wcs>
Jarid2<tm1Wcs>
Mpdz<em1J>
4932431P20Rik<em2Wtsi>
5330434G04Rik<em1Wtsi>
Alpk1<em2Wtsi>
Brcc3<em1Wtsi>
Brd2<em2Wtsi>
Cadm1<tm1.2Brd>
Ccdc6<em2Wtsi>
Cdh23<v>
Cdk4<R24C>
Cdyl<em2Wtsi>
Crim1<em1Wtsi>
Csmd1<em1Wtsi>
Cybb<tm1Din>
Dcn<em1Wtsi>
Dcun1d3<em2Wtsi>
Dffb<em2Wtsi>
Dlg4<tm1Grnt>
Endou<tm1>
Fut2<em1Wtsi>
Fut8<em1Wtsi>
Gbp5<em2Wtsi>
Glyatl3<em2Wtsi>
Gpatch1<em2Wtsi>
Hao2<em2Wtsi>
Herc1<em4Wtsi>
Herc1<em2Wtsi>
Herc1<em1Wtsi>
Hpf1<em2Wtsi>
Ifitm3<tm1Masu>
Ighm<tm1Cgn>
Il18rap<em1Wtsi>
Itln1<em1Wtsi>
Josd1<em1Wtsi>
Kera<em2Wtsi>
Lmna<G609G>
Macrod1<em2Wtsi>
Mbl2<em2Wtsi>
Med23<em2Wtsi>
Mir96<Tm2.2WTSI>
Mir96<Tm3.2WTSI>
Olfr168<KO>
Pkhd1<Del2>
Plet1<em1Wtsi>
Prss53<em2Wtsi>
Prss53<Q30R>
Rassf1<tm1.2Brd>
Rimbp2<em2Wtsi>
Sema7a<tm1Alk>
Trim21<em2Wtsi>
Usp37<em2Wtsi>
Zfp763<em2Wtsi>
Adad1<em1J>
Adad2<em1J>
Exoc4<em1J>
Tgm2<tm1Rmgr>
Ttll10<em1J>
Brd2<em2Wtsi>
Tg(CMV-cre)1Cgn
Tg(ACTFLPe)9205Dym
Myo7a<sh1-6J>
Myo6<sv>
Dlg4<tm1Grnt>
Tyr<c-Wtsi>
Cdh23<CBA/CaJ>
Cdh23<ahl>

**Comment by jmason-ebi** [comment]
Done
