### ISSUE TITLE
Ability to fix the contents of the consoritum papers tab

### ISSUE THREAD

**Issue by viomunoz** [mpi2/impc-publication-curation#41]
**Issue:**
At least two papers were identified that are not consortium papers. We do not know how they got there.
https://www.mousephenotype.org/data/publications

=====

![Screenshot 2021-04-23 at 18.10.22.png](https://images.zenhubusercontent.com/5e271bb2e33c5e6b469a910f/79c037db-ccbd-4057-913b-4b3d95671000)

=====
![Screenshot 2021-04-23 at 18.10.48.png](https://images.zenhubusercontent.com/5e271bb2e33c5e6b469a910f/3d6aaeee-ad6e-43ee-b9a7-2ba1936d67ec)
=====
**Requirements:**
Ability to deselect as consortium papers.

**Comment by viomunoz** [comment]
These papers were removed. However, the curation app interface does not allow to do this. Moving this ticket to the backlog as nobody has time to work on this for the time being.

**Comment by ficolo** [comment]
Apologies for not replying this thread, You actually can do it on the Interface.

1. Go to the reviewed tab and filter by Consortium Papers on the Filter side bar:

![Screenshot 2021-06-03 at 12 52 58](https://user-images.githubusercontent.com/2343039/120640728-b9efa580-c46a-11eb-88f3-f61cae51cf56.png)

2. Uncheck the Consortium:

![Screenshot 2021-06-03 at 12 54 00](https://user-images.githubusercontent.com/2343039/120640852-dd1a5500-c46a-11eb-9777-3c5fc1d23d12.png)

3. Click the updated button:

![Screenshot 2021-06-03 at 12 55 47](https://user-images.githubusercontent.com/2343039/120641078-1a7ee280-c46b-11eb-8afd-4a8717eb39d7.png)

**Comment by jmason-ebi** [comment]
That's how I did it -- through the interface.  I think this is done
