### ISSUE TITLE
Literature curation: allele extraction from papers studying 100+ alleles

### ISSUE THREAD

**Issue by viomunoz** [mpi2/impc-publication-curation#55]
Gene pages are going have a Publication section. This is in beta currently. 
UX meeting 13 October 2021: this section is to report papers studying IMPC alleles.

**Requirement:**
We need to make sure that all alleles from papers studying 100+ alleles are included in our list with curated papers using IMPC data and products.

**Steps:**
- [x] 1.-Make a list of the papers studying 100+ IMPC alleles.
- [x] 2.-Extract all alleles.
- [x] 3.-Ingest alleles.

**Comment by viomunoz** [comment]
Steps 1 and 2 completed. 

Summary table:

![image.png](https://images.zenhubusercontent.com/5e271bb2e33c5e6b469a910f/31be2cdc-f5e1-4bcc-a645-eaa2efb0edae)




The Pereira et al. paper only refers to 11 alleles, but they conducted secondary phenotyping. They were requested from the authors, so we may as well make sure they are reported in the curated list.

**Comment by ficolo** [comment]
This has been done, there are some small differences on the allele counts:

| PMID            | Reported on the issue | Loaded on the app |
|-----------------|-----------------------|-------------------|
|        32245826 | 1342                  | 1346              |
| 32553114        | 12                    | 15                |
| 30973865        | 1312                  | 1310              |
| 31844327        | 535                  | 535               |
| 31371714        | 1688                  | 1688              |
