### ISSUE TITLE
Consortium papers: Adding these papers to the IMPC publication list

### ISSUE THREAD

**Issue by viomunoz** [mpi2/impc-publication-curation#58]
The following papers are  consortium papers that need to be added to the list of IMPC papers (may be "manually"?) as they were not picked up by literature curation app.

These papers also need to be marked as consortium papers.

As a validation, they will need to appear here:
https://www.mousephenotype.org/data/publications

(There is a separate ticket to investigate why the  literature curation app did not pick these papers up #59)

Papers:
- PMC?	29600991	2018-04-01	YES	Response to "Unexpected mutations after CRISPR-Cas9 editing in vivo".	Nutter, Lauryl M J;Heaney, Jason D;Lloyd, K C Kent;Murray, Stephen A;Seavitt, John R;Skarnes, William C;Teboul, Lydia;Brown, Steve D M;Moore, Mark
- The occurrence of tarsal injuries in male mice of C57BL/6N substrains in multiple international mouse facilities	Morphology	Published	2020	PLoS ONE	https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0230162
- Universal Southern blot protocol with cold or radioactive probes for the validation of alleles obtained by homologous recombination	Production	Published	2020	Methods	doi: 10.1016/j.ymeth.2020.06.011
- Variability in Genome Editing Outcomes: Challenges for Research Reproducibility and Clinical Safety	Production	Published	2020	Molecular Therapy	https://www.sciencedirect.com/science/article/pii/S1525001620301490
- Machine learning-based automated phenotyping of inflammatory nocifensive behavior in mice	Pain	Published	2020	Molecular Pain	https://pubmed.ncbi.nlm.nih.gov/32955381/
- Cage-lid hanging behavior as a translationally relevant measure of pain in mice	Pain	Published	2020	Pain	https://journals.lww.com/pain/Abstract/9000/Cage_lid_hanging_behavior_as_a_translationally.98198.aspx
- Identifying genetic determinants of inflammatory pain in mice using a large-scale gene-targeted screen	Pain	Published	2021	Pain	doi.org/10.1097/j.pain.0000000000002481
- Progress towards completing the mutant mouse null resource	Production	Published	2021	Mammalian Genome	https://link.springer.com/article/10.1007/s00335-021-09905-0

**Comment by viomunoz** [comment]
Another paper that needs to be added and marked as consortium paper, as per author confirmation:

- PMC5350237 27905063 2017-04-01 Efficient gene targeting in mouse zygotes mediated by CRISPR/Cas9-protein. Jung, Chris J;Zhang, Junli;Trenchard, Elizabeth;Lloyd, Kent C;West, David B;Rosen, Barry;de Jong, Pieter J https://link.springer.com/article/10.1007%2Fs11248-016-9998-5 

The following paper also needs to be added, but NOT marked as consortium paper:

- PMC5350237 27905063 2017-04-01 Efficient gene targeting in mouse zygotes mediated by CRISPR/Cas9-protein. Jung, Chris J;Zhang, Junli;Trenchard, Elizabeth;Lloyd, Kent C;West, David B;Rosen, Barry;de Jong, Pieter J https://link.springer.com/article/10.1007%2Fs11248-016-9998-5

**Comment by ficolo** [comment]
I've just added them manually, [this feature has been included for a while in the tool](https://github.com/mpi2/impc-publication-curation/issues/13). You can achieve this by clicking the plus button on the bottom right of the screen and then submitting the paper's PMID:

![Screenshot 2022-01-04 at 14.19.38.png](https://images.zenhubusercontent.com/5e2731c352024f33e54b74eb/252a9b96-3b88-4f05-8b6c-5b1f6a5a51bf)

![Screenshot 2022-01-04 at 14.20.39.png](https://images.zenhubusercontent.com/5e2731c352024f33e54b74eb/f2e75855-3ed1-40b6-94cd-af23777f5667)

The paper gets added automatically to the Pending tab and then you can perform the regular curation process.

**Note:** Not in PubMed Central: Identifying genetic determinants of inflammatory pain in mice using a large-scale gene-targeted screen Pain Published 2021 Pain doi.org/10.1097/j.pain.0000000000002481 (the tool only has support for papers recorded on PubMed)

**Comment by viomunoz** [comment]
Ok, that is great. 
Except for "Identifying genetic determinants of inflammatory pain in mice using a large-scale gene-targeted screen" which could not be added -- are the papers in the pending list to be curated or already confirmed as IMPC papers?
Can "Identifying genetic determinants of inflammatory pain in mice using a large-scale gene-targeted screen" be added somehow, so it appears in the website (and then further filtered to the gene pages)?

**Comment by rwilson-ebi** [comment]
No way to add a paper without a PubMed ID, but probably just a timing.
