### ISSUE TITLE
No option for gene that needs to be linked to paper in the dropdown menu - cannot add

### ISSUE THREAD

**Issue by viomunoz** [mpi2/impc-publication-curation#62]
**Issue:**
I am trying to add an allele to a paper, but I have no options for that gene in the dropdown menu :

These are some of the cases, but there are more:
[1] Pde4c
[2] Osm
[3] Vsir
[4] Mtss2
[5] Spry
[6] Gpr180
[7] Lat & Mx2
[8] Ep400
[9] Magee2
[10] F2rl1
[11] Megf10
[12] Nphp4, Iqcb1, Cep290, Sdccag8, Anks6, Traf3ip1, Cc2d2a

When adding an allele to a paper, an autocomplete option is presented.

I am trying to add Pde4c<tm1.1(KOMP)Wtsi> but no options are presented for this gene Pde4c:

= = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =

![image.png](https://images.zenhubusercontent.com/5e271bb2e33c5e6b469a910f/51661ffb-5c5d-490f-bec9-5e5c6b2013ae)
= = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =

**Requirements:**
We need to be able to add these genes to these papers. 

**Details:**
[1] Gene Pde4c
This is the paper:
Assessment of PDE4 Inhibitor-Induced Hypothermia as a Correlate of Nausea in Mice.
open_in_new PubMed ID: 34943270  open_in_new Full text 
Boyd A, Aragon IV, Rich J, McDonough W, Oditt M, Irelan D, Fiedler E, Abou Saleh L, Richter W.
Biology - December, 2021

The allele I would like to add: Pde4c<tm1.1(KOMP)Wtsi>
 https://www.mousephenotype.org/data/genes/MGI:99556#order

[2] Gene Osm
This is hte paper:
Heterocellular OSM-OSMR signalling reprograms fibroblasts to promote pancreatic cancer growth and metastasis.
open_in_new PubMed ID: 34921158  open_in_new Full text 
Lee BY, Hogg EKJ, Below CR, Kononov A, Blanco-Gomez A, Heider F, Xu J, Hutton C, Zhang X, Scheidt T, Beattie K, Lamarca A, McNamara M, Valle JW, Jørgensen C.
Nature communications - December, 2021

The allele I am trying to add:
Osm<tm1a(KOMP)Wtsi> https://www.mousephenotype.org/data/genes/MGI:104749

[3] Gene Vsir:
The paper:
Kidney VISTA prevents IFN-γ/IL-9 axis-mediated tubulointerstitial fibrosis after acute glomerular injury.
open_in_new PubMed ID: 34752423  open_in_new Full text 
Kim MG, Yun D, Kang CL, Hong M, Hwang J, Moon KC, Jeong CW, Kwak C, Kim DK, Oh KH, Joo KW, Kim YS, Lee DS, Han SS.
The Journal of clinical investigation - January, 2022

The allele to add: Vsir<tm1(KOMP)Vlcg>
https://www.mousephenotype.org/data/genes/MGI:1921298#order

[4] Mtss2
Paper:
Revisiting I-BAR Proteins at Central Synapses.
open_in_new PubMed ID: 34975417  open_in_new Full text 
Chatzi C, Westbrook GL.
Frontiers in neural circuits - December, 2021
Allele: Mtss2<tm1a(KOMP)Wtsi> https://www.mousephenotype.org/data/genes/MGI:3039591#order

[5] Spry4
Regulation of positive and negative selection and TCR signaling during thymic T cell development by capicua.
open_in_new PubMed ID: 34895467  open_in_new Full text 
Kim S, Park GY, Park JS, Park J, Hong H, Lee Y.
eLife - December, 2021
Allele:
Spry4<tm1a(KOMP)Mbp>
https://www.mousephenotype.org/data/genes/MGI:1345144#order

[6] Gpr180
GPR180 is a component of TGFβ signalling that promotes thermogenic adipocyte function and mediates the metabolic effects of the adipocyte-secreted factor CTHRC1.
open_in_new PubMed ID: 34880217  open_in_new Full text  open_in_new Cites IMPC Paper - PMID:21677750
Balazova L, Balaz M, Horvath C, Horváth Á, Moser C, Kovanicova Z, Ghosh A, Ghoshdastider U, Efthymiou V, Kiehlmann E, Sun W, Dong H, Ding L, Amri EZ, Nuutila P, Virtanen KA, Niemi T, Ukropcova B, Ukropec J, Pelczar P, Lamla T, Hamilton B, Neubauer H, Wolfrum C.
Nature communications - December, 2021
Allele:
Gpr180<tm1a(KOMP)Wtsi>
https://www.mousephenotype.org/data/genes/MGI:1930949#order

[7] Lat & Mx2
Paper:
ProMetIS, deep phenotyping of mouse models by combined proteomics and metabolomics analysis.
open_in_new PubMed ID: 34862403  open_in_new Full text  open_in_new Cites IMPC Paper - PMID:22940749open_in_new Cites IMPC Paper - PMID:28650483open_in_new Cites IMPC Paper - PMID:29626206
Imbert A, Rompais M, Selloum M, Castelli F, Mouton-Barbosa E, Brandolini-Bunlon M, Chu-Van E, Joly C, Hirschler A, Roger P, Burger T, Leblanc S, Sorg T, Ouzia S, Vandenbrouck Y, Médigue C, Junot C, Ferro M, Pujos-Guillot E, de Peredo AG, Fenaille F, Carapito C, Herault Y, Thévenot EA.
Scientific data - December, 2021
Alleles:
Lat<em1(IMPC)Ics> https://www.mousephenotype.org/data/genes/MGI:1342293
 Mx2<em1(IMPC)Ics> https://www.mousephenotype.org/data/genes/MGI:97244

![Screenshot 2022-01-24 at 14.33.05.png](https://images.zenhubusercontent.com/5e271bb2e33c5e6b469a910f/2707ce85-646d-4635-a10b-0f7597a3cf38)

![Screenshot 2022-01-24 at 14.37.03.png](https://images.zenhubusercontent.com/5e271bb2e33c5e6b469a910f/c6e12f2e-b530-48a1-8ff8-ccfc63dbe2a3)

[8] Ep400
Histone variant H2A.Z regulates zygotic genome activation.
open_in_new PubMed ID: 34853314  open_in_new Full text  open_in_new Cites IMPC Paper - PMID:27626380
Ibarra-Morales D, Rauer M, Quarato P, Rabbani L, Zenk F, Schulte-Sasse M, Cardamone F, Gomez-Auli A, Cecere G, Iovino N.
Nature communications - December, 2021
Ep400<tm1b(EUCOMM)Hmgu>
https://www.mousephenotype.org/data/genes/MGI:1276124

[9] Magee2
A Positively Selected MAGEE2 LoF Allele Is Associated with Sexual Dimorphism in Human Brain Size and Shows Similar Phenotypes in Magee2 Null Mice.
open_in_new PubMed ID: 34464968  open_in_new Full text  open_in_new Cites IMPC Paper - PMID:26147094open_in_new Cites IMPC Paper - PMID:28650954
Szpak M, Collins SC, Li Y, Liu X, Ayub Q, Fischer MC, Vancollie VE, Lelliott CJ, Xue Y, Yalcin B, Yang H, Tyler-Smith C.
Molecular biology and evolution - December, 2021

Allele: Magee2<em1(IMPC)Wtsi>
https://www.mousephenotype.org/data/genes/MGI:2148316

[10] F2rl1
Myeloid Protease-Activated Receptor-2 Contributes to Influenza A Virus Pathology in Mice.
open_in_new PubMed ID: 34925374  open_in_new Full text  open_in_new Cites IMPC Paper - PMID:21677750
Gunther RC, Bharathi V, Miles SD, Tumey LR, Schmedes CM, Tatsumi K, Bridges MD, Martinez D, Montgomery SA, Beck MA, Camerer E, Mackman N, Antoniak S.
Frontiers in immunology - December, 2021

Allele: F2rl1<tm1a(EUCOMM)Wtsi> https://www.mousephenotype.org/data/genes/MGI:101910#order

[11] Megf10
Stroke subtype-dependent synapse elimination by reactive gliosis in mice.
open_in_new PubMed ID: 34836962  open_in_new Full text 
Shi X, Luo L, Wang J, Shen H, Li Y, Mamtilahun M, Liu C, Shi R, Lee JH, Tian H, Zhang Z, Wang Y, Chung WS, Tang Y, Yang GY.
Nature communications - November, 2021
Allele:
Megf10<tm1(KOMP)Vlcg>
https://www.mousephenotype.org/data/genes/MGI:2685177#order

[12]
Nephronophthisis-Pathobiology and Molecular Pathogenesis of a Rare Kidney Genetic Disease.
open_in_new PubMed ID: 34828368  open_in_new Full text 
Gupta S, Ozimek-Kulik JE, Phillips JK.
Genes - November, 2021
Nphp4em1(IMPC)Bay;
Iqcb1em1(IMPC)Bay;
Cep290em1(IMPC)Mbp; 
Sdccag8tm1a(EUCOMM)Wtsi;
Anks6tm1b(KOMP)Wtsi;
Traf3ip1em1(IMPC)Bay
Cc2d2atm1a(EUCOMM)Wtsi

**Comment by ficolo** [comment]
I have updated the allele index for the publications tool, all the alleles listed here seems to be there now.

**Comment by viomunoz** [comment]
All the papers in that list could have the alleles added to. This ticket can now be closed.
